Fix error opening editor on Java 25
On Java 25 due to https://bugs.openjdk.org/browse/JDK-8024695 aka `new
File("")` returns true,
causes Error log like:
!ENTRY org.eclipse.chemclipse.converter 4 0 2026-03-30 12:50:17.619
!MESSAGE  (No such file or directory)
!STACK 0
java.io.FileNotFoundException:  (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:185)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
	at org.eclipse.chemclipse.xxd.converter.supplier.ocx.internal.methods.IMethodReader.convert(IMethodReader.java:40)
	at org.eclipse.chemclipse.xxd.converter.supplier.ocx.methods.MethodImportConverter.convert(MethodImportConverter.java:52)
	at org.eclipse.chemclipse.converter.methods.MethodConverter.convert(MethodConverter.java:93)
	at org.eclipse.chemclipse.converter.methods.MethodConverter.convert(MethodConverter.java:77)
	at org.eclipse.chemclipse.converter.adapters.MethodAdapterFactory.convertFile(MethodAdapterFactory.java:55)
	at org.eclipse.chemclipse.converter.adapters.MethodAdapterFactory.getAdapter(MethodAdapterFactory.java:47)
	at org.eclipse.core.internal.runtime.AdapterManager.lambda$13(AdapterManager.java:312)